server:
  port: 7001
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      filter:
        routes:
          - id: gateway-service
            uri: https://blog.csdn.net
            predicates:
              - Path=/meteor_93