server:
  port: 8090
spring:
  application:
    name: spring-cloud-consumer1
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
feign:
  hystrix:
    enabled: true