server:
  port: 9080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zdatbit/springcloud.git # git项目地址
          search-paths: spring-config  # git配置文件的相对目录
          default-label: main